name: GitHub Actions - build & test
run-name: ${{ github.actor }} build & test 🚀
on: [push]
jobs:
  build_and_test:
    name: wlocate rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
      - run: cargo test